name: behat_drupal
recipe: drupal9
config:
  webroot: /docroot
services:
  appserver:
    build:
      - composer install
  selenium:
    type: compose
    services:
      image: selenium/standalone-chrome
      hostname: chrome
      user: root
      ports:
        - "4444:4444"
      volumes:
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
tooling:
  behat:
    service: appserver
    cmd:
      - behat
